#!/bin/bash -e

echo "------------------------"
echo "Building images"
echo "------------------------"
cd ./dehydrated
docker build --tag $DOCKER_USERNAME/dehydrated:latest \
  --file Dockerfile .

echo "------------------------"
echo "Pushing images"
echo "------------------------"
docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
docker push $DOCKER_USERNAME/dehydrated:latest
